# Site settings
baseURL = "https://kowalinski.dev"
languageCode = "pl"
title = "Szymon Kowaliński"
theme = "hugo-split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Szymon Kowaliński"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  # Metadata for search engines and social sharing
  author = "Szymon Kowaliński"
  description = "Personal site of Szymon Kowaliński"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "images/favicon.ico"
  [params.custom.css]
    enable = true

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/avatar.jpeg"
      position = "center center"

    # Video
#    [params.visual.video]
#      enable = false
#      mute = true
#      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "My work"

      [[params.links.list1.link]]
        text = "<i class='fas fa-code-branch' style='font-style: normal;'></i> Projects"
        url = "/about"
#        dotted = true

      [[params.links.list1.link]]
        text = "<i class='fab fa-github fa-lg' style='font-style: normal;'></i> Github"
        url = "https://github.com/Simon-the-Shark"
#        dotted = true

      [[params.links.list1.link]]
        text = "About me"
        url = "/about"
#        dotted = true

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Connect"

      [[params.links.list2.link]]
        text = "<i class='fa fa-envelope fa-lg' style='font-style: normal;'></i> Email"
        url = "mailto:personal@kowalinski.dev"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/simon_rekin/"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/szymekkowalinski"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Languages"

      [[params.links.list3.link]]
        text = "Polski"
        url = "#"

#      [[params.links.list3.link]]
#        text = "Link Two"
#        url = "#"
#
#      [[params.links.list3.link]]
#        text = "Link Three"
#        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split