# Site settings
baseURL = "https://kowalinski.dev"
title = "Szymon Kowaliński"
theme = "hugo-split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Szymon Kowaliński"

defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"

[params]
  author = "Szymon Kowaliński"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  favicon = "images/favicon.ico"
  [params.custom.css]
    enable = true

  [params.visual]
    [params.visual.image]
      enable = true
      file = "images/avatar.jpeg"
      position = "center center"


[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    description = "Szymon Kowaliński, Django, Python and Flutter, Dart software developer. Academic Highschool of Wrocław University of Technology"

  [languages.pl]
    languageName = "Polska wersja"
    contentDir = "content/polish"
    weight = 2
    description = "Szymon Kowaliński. Programista Django, Python i Flutter, Dart. Liceum Akademickie Politechniki Wrocławskiej"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split